import { useEffect, useState } from 'react';
import { Bell, BellOff, LoaderCircle, Smartphone, Trash2 } from 'lucide-react';
import { DEFAULT_NOTIFICATION_PREFERENCES, loadNotificationSettings, revokeNotificationDevice, saveNotificationPreferences, type NotificationDevice, type NotificationPreferences } from '../../core/notifications/notificationApi';
import { enableNotifications, notificationPermission } from '../../core/notifications/notificationService';

const choices:Array<{key:keyof NotificationPreferences;label:string;detail:string}>=[
  {key:'taskAssigned',label:'Action assigned',detail:'New KCP Flow Actions assigned to you, your Role Set or location'},
  {key:'taskOverdue',label:'Action overdue',detail:'Assigned Actions that have passed their due time'},
  {key:'approvalRequested',label:'Approval requested',detail:'Protected exceptions awaiting your decision'},
  {key:'approvalCompleted',label:'Approval completed',detail:'Your submitted exception was approved or rejected'},
  {key:'lowStock',label:'Low stock',detail:'Location items reach their configured threshold'},
  {key:'incomingTransfer',label:'Incoming transfer',detail:'A transfer is ready for your location'},
  {key:'purchaseOrderDelivery',label:'PO delivery reminder',detail:'An open purchase order is due for delivery'}
];
export function NotificationSettings({workspaceId,deviceId,onCurrentRevoked}:{workspaceId:string;deviceId:string;onCurrentRevoked:()=>void}){
  const [preferences,setPreferences]=useState(DEFAULT_NOTIFICATION_PREFERENCES);const [devices,setDevices]=useState<NotificationDevice[]>([]);const [permission,setPermission]=useState<string>('unknown');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  useEffect(()=>{void Promise.all([loadNotificationSettings(workspaceId),notificationPermission()]).then(([result,state])=>{setPreferences({...DEFAULT_NOTIFICATION_PREFERENCES,...result.preferences});setDevices(result.devices.map((item)=>({...item,current:item.id===deviceId})));setPermission(state);}).catch(()=>setMessage('Notification settings are unavailable until KCP reconnects.'));},[deviceId,workspaceId]);
  async function enable(){setBusy(true);setMessage('');try{const result=await enableNotifications();setPermission(result);setMessage(result==='granted'?'Notifications enabled on this device.':result==='denied'?'Notifications are disabled in system settings.':'Push notifications require the installed Android or iOS app.');}finally{setBusy(false);}}
  async function toggle(key:keyof NotificationPreferences){const next={...preferences,[key]:!preferences[key]};setPreferences(next);setBusy(true);try{const result=await saveNotificationPreferences(workspaceId,next);setPreferences(result.preferences);setMessage('Notification preferences saved.');}catch{setPreferences(preferences);setMessage('Preferences could not be saved.');}finally{setBusy(false);}}
  async function revoke(id:string){if(id===deviceId&&!window.confirm('Revoke notifications and the mobile session for this device?'))return;setBusy(true);try{await revokeNotificationDevice(workspaceId,id);setDevices((items)=>items.filter((item)=>item.id!==id));setMessage('Device access and notification token revoked.');if(id===deviceId)onCurrentRevoked();}finally{setBusy(false);}}
  return <section className="notification-settings"><header><div><p className="settings-label">Notifications</p><h2>Operational alerts</h2></div><span className={`notification-permission is-${permission}`}>{permission==='granted'?<Bell size={18}/>:<BellOff size={18}/>} {permission}</span></header>{message&&<div className="notification-message" role="status">{message}</div>}{permission!=='granted'&&<button className="button button-secondary" type="button" onClick={()=>void enable()} disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<Bell size={17}/>} Enable notifications</button>}<div className="notification-preferences">{choices.map((choice)=><label key={choice.key}><span><strong>{choice.label}</strong><small>{choice.detail}</small></span><input type="checkbox" checked={preferences[choice.key]} onChange={()=>void toggle(choice.key)} disabled={busy}/></label>)}</div><h3>Registered devices</h3><div className="notification-devices">{devices.map((device)=><div key={device.id}><Smartphone size={18}/><span><strong>{device.deviceName||device.platform}</strong><small>{device.platform} · v{device.appVersion||'unknown'}{device.current?' · This device':''}</small></span><button className="icon-button" type="button" onClick={()=>void revoke(device.id)} disabled={busy} aria-label={`Revoke ${device.deviceName||device.platform}`}><Trash2 size={16}/></button></div>)}</div></section>;
}
