import { Capacitor } from '@capacitor/core';
import { Directory, Filesystem } from '@capacitor/filesystem';
import { Share } from '@capacitor/share';
import type { PurchaseOrderSummary } from './purchaseOrderApi';

export async function buildPurchaseOrderPdf(order: PurchaseOrderSummary, workspaceName: string): Promise<Blob> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const width = doc.internal.pageSize.getWidth();
  const left = 15;
  let y = 18;
  const ensure = (height: number) => { if (y + height <= 282) return; doc.addPage(); y = 18; };
  doc.setFillColor(9, 24, 43); doc.rect(0, 0, width, 34, 'F');
  doc.setTextColor(255, 255, 255); doc.setFont('helvetica', 'bold'); doc.setFontSize(19); doc.text('KCP', left, 16);
  doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.text('Kitchen Cost Pro · Purchase Order', left, 23);
  doc.setFontSize(15); doc.setFont('helvetica', 'bold'); doc.text(order.poNumber, width - left, 18, { align: 'right' });
  doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.text(human(order.status), width - left, 24, { align: 'right' });
  y = 44; doc.setTextColor(20, 35, 54); doc.setFontSize(11); doc.setFont('helvetica', 'bold'); doc.text(workspaceName || 'KCP Workspace', left, y);
  y += 8; doc.setFontSize(8); doc.setFont('helvetica', 'normal');
  const meta = [
    [`Supplier`, order.supplierName], [`Receiving location`, order.location.name],
    [`Order date`, date(order.orderedAt || order.createdAt)], [`Expected delivery`, date(order.expectedAt)],
    [`Supplier email`, order.supplierEmail || 'Not recorded'], [`Supplier phone`, order.supplierPhone || 'Not recorded']
  ];
  meta.forEach(([label, value], index) => { const column = index % 2; const row = Math.floor(index / 2); const x = left + column * 92; const lineY = y + row * 11; doc.setTextColor(100, 116, 134); doc.text(label.toUpperCase(), x, lineY); doc.setTextColor(20, 35, 54); doc.setFont('helvetica', 'bold'); doc.text(truncate(value, 42), x, lineY + 4); doc.setFont('helvetica', 'normal'); });
  y += 38;
  doc.setFillColor(236, 241, 247); doc.rect(left, y, width - left * 2, 8, 'F'); doc.setFont('helvetica', 'bold'); doc.setTextColor(52, 66, 83); doc.text('ITEM', left + 2, y + 5.4); doc.text('QTY', 111, y + 5.4); doc.text('PACK', 132, y + 5.4); doc.text('UNIT COST', 153, y + 5.4); doc.text('TOTAL', width - left - 2, y + 5.4, { align: 'right' }); y += 8;
  order.items.forEach((line) => { ensure(12); doc.setDrawColor(224, 230, 238); doc.line(left, y + 11, width - left, y + 11); doc.setFont('helvetica', 'bold'); doc.setTextColor(23, 38, 58); doc.text(truncate(line.name, 43), left + 2, y + 5); doc.setFont('helvetica', 'normal'); doc.setTextColor(103, 119, 136); doc.text(truncate(line.sku || line.category || line.baseUom, 43), left + 2, y + 9); doc.setTextColor(23, 38, 58); doc.text(`${quantity(line.quantity)} ${line.purchaseUom}`, 111, y + 6); doc.text(quantity(line.packSize), 132, y + 6); doc.text(money(line.unitCost), 153, y + 6); doc.text(money(line.lineTotalEx), width - left - 2, y + 6, { align: 'right' }); y += 12; });
  ensure(36); y += 5; const totalsX = width - left - 66; doc.setFontSize(9); [['Subtotal', order.totalEx], ['VAT', order.totalVat], ['Total', order.totalInc]].forEach(([label, value], index) => { if (index === 2) { doc.setFillColor(232, 226, 255); doc.rect(totalsX - 3, y - 5, 69, 10, 'F'); doc.setFont('helvetica', 'bold'); } doc.setTextColor(55, 65, 81); doc.text(String(label), totalsX, y); doc.text(money(Number(value)), width - left - 2, y, { align: 'right' }); y += 9; });
  if (order.note) { ensure(24); y += 4; doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.text('ORDER NOTE', left, y); y += 5; doc.setFont('helvetica', 'normal'); const note = doc.splitTextToSize(order.note, width - left * 2); doc.text(note, left, y); }
  const pages = doc.getNumberOfPages(); for (let page = 1; page <= pages; page += 1) { doc.setPage(page); doc.setFontSize(7); doc.setTextColor(130, 143, 157); doc.text(`Generated by KCP Lite · ${new Date().toLocaleString('en-ZA')}`, left, 291); doc.text(`Page ${page} of ${pages}`, width - left, 291, { align: 'right' }); }
  return doc.output('blob');
}

export async function sharePurchaseOrderPdf(order: PurchaseOrderSummary, workspaceName: string) {
  const blob = await buildPurchaseOrderPdf(order, workspaceName); const filename = `${safe(order.poNumber || order.id)}.pdf`;
  if (Capacitor.isNativePlatform()) {
    const data = await blobToBase64(blob); await Filesystem.writeFile({ path: filename, data, directory: Directory.Cache });
    const file = await Filesystem.getUri({ path: filename, directory: Directory.Cache });
    await Share.share({ title: order.poNumber, text: `Purchase order ${order.poNumber} for ${order.supplierName}`, files: [file.uri], dialogTitle: 'Share purchase order' }); return;
  }
  const file = new File([blob], filename, { type: 'application/pdf' });
  if (navigator.share && (!navigator.canShare || navigator.canShare({ files: [file] }))) { await navigator.share({ title: order.poNumber, text: `Purchase order for ${order.supplierName}`, files: [file] }); return; }
  const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; document.body.appendChild(anchor); anchor.click(); anchor.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function emailPurchaseOrder(order: PurchaseOrderSummary) {
  if (!order.supplierEmail) throw new Error('This supplier does not have an email address in KCP.');
  const subject = encodeURIComponent(`${order.poNumber} · ${order.location.name}`);
  const body = encodeURIComponent(`Hello ${order.supplierName},\n\nPlease find purchase order ${order.poNumber} for delivery to ${order.location.name} by ${date(order.expectedAt)}.\n\nOrder total: ${money(order.totalInc)}\n\nPlease attach the PDF from KCP Lite before sending.\n`);
  window.location.href = `mailto:${encodeURIComponent(order.supplierEmail)}?subject=${subject}&body=${body}`;
}

async function blobToBase64(blob: Blob) { const buffer = new Uint8Array(await blob.arrayBuffer()); let binary = ''; for (let index = 0; index < buffer.length; index += 0x8000) binary += String.fromCharCode(...buffer.subarray(index, index + 0x8000)); return btoa(binary); }
function safe(value: string) { return String(value || 'purchase-order').replace(/[^a-z0-9_-]+/gi, '-').replace(/^-+|-+$/g, '') || 'purchase-order'; }
function truncate(value: string, max: number) { const clean = String(value || ''); return clean.length > max ? `${clean.slice(0, max - 1)}…` : clean; }
function quantity(value: number) { return new Intl.NumberFormat('en-ZA', { maximumFractionDigits: 3 }).format(Number(value || 0)); }
function money(value: number) { return `R ${new Intl.NumberFormat('en-ZA', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(value || 0))}`; }
function date(value: string) { const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? 'Not set' : new Intl.DateTimeFormat('en-ZA', { dateStyle: 'medium' }).format(parsed); }
function human(value: string) { return String(value || '').replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }
