import { useEffect, useState } from 'react';
import './ApprovalPoliciesAdmin.css';

type Operation='stock_take_variance'|'high_value_wastage'|'large_transfer'|'purchase_order'|'manual_stock_adjustment'|'manufacturing_exception';
type Level={level:number;label:string;minValue:number;maxValue:number|null;approvalsRequired:number;roles:string[];roleLimits:Record<string,number|null>};
type Policy={id?:string;operationType:Operation;name:string;locationId:string;thresholdValue:number;currency:string;blockSelfApproval:boolean;levels:Level[];active?:boolean};
type RawPolicy=Record<string,any>;
type Props={workspaceId:string;api:<T>(resource:string,options?:{method?:'GET'|'POST'|'PUT'|'DELETE';payload?:unknown})=>Promise<T>;locations:Array<{id:string;name:string}>;roles:string[]};
const operations:Record<Operation,string>={stock_take_variance:'Stock take variance',high_value_wastage:'High-value wastage',large_transfer:'Large or unusual transfer',purchase_order:'Purchase orders',manual_stock_adjustment:'Manual stock adjustments',manufacturing_exception:'Manufacturing shortages / yield loss'};
const blank=():Policy=>({operationType:'stock_take_variance',name:'Stock take variance',locationId:'',thresholdValue:500,currency:'ZAR',blockSelfApproval:true,levels:[{level:1,label:'Manager approval',minValue:0,maxValue:null,approvalsRequired:1,roles:['manager'],roleLimits:{manager:50000}}]});
function normalize(row:RawPolicy):Policy{return{id:String(row.id),operationType:String(row.operation_type||row.operationType) as Operation,name:String(row.name||''),locationId:String(row.location_id||row.locationId||''),thresholdValue:Number(row.threshold_value??row.thresholdValue??0),currency:String(row.currency||'ZAR'),blockSelfApproval:Boolean(row.blockSelfApproval??row.block_self_approval),levels:(row.levels||[]).map((level:RawPolicy,index:number)=>({level:index+1,label:String(level.label||`Level ${index+1}`),minValue:Number(level.minValue||0),maxValue:level.maxValue==null?null:Number(level.maxValue),approvalsRequired:Math.max(1,Number(level.approvalsRequired||1)),roles:Array.isArray(level.roles)?level.roles.map(String):[],roleLimits:level.roleLimits||{}})),active:Boolean(row.active)}};

export function ApprovalPoliciesAdmin({api,locations,roles}:Props){
  const [policies,setPolicies]=useState<Policy[]>([]);const [draft,setDraft]=useState<Policy>(blank());const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const load=async()=>{const result=await api<{policies:RawPolicy[]}>('approval-policies');setPolicies((result.policies||[]).map(normalize));};useEffect(()=>{void load();},[]);
  async function save(){setMessage('');if(!draft.name.trim()||!draft.levels.length||draft.levels.some((level)=>!level.roles.length||level.approvalsRequired<1)){setMessage('A policy name and at least one valid approval level are required.');return;}setBusy(true);try{await api(`approval-policies${draft.id?`/${encodeURIComponent(draft.id)}`:''}`,{method:draft.id?'PUT':'POST',payload:draft});setMessage('Approval policy saved. New submissions use this version; existing requests keep their immutable snapshot.');setDraft(blank());await load();}finally{setBusy(false);}}
  function patchLevel(index:number,patch:Partial<Level>){setDraft({...draft,levels:draft.levels.map((level,i)=>i===index?{...level,...patch}:level)});}
  return <section className="approval-policy-admin"><header><div><p>Exception control</p><h1>Approval policies</h1></div><button type="button" onClick={()=>setDraft(blank())}>New policy</button></header>{message&&<div className="approval-policy-message" role="status">{message}</div>}<div className="approval-policy-layout"><aside>{policies.map((policy)=><button type="button" key={policy.id} onClick={()=>setDraft(policy)}><strong>{policy.name}</strong><small>{operations[policy.operationType]} · from {policy.currency} {policy.thresholdValue.toLocaleString()}</small><span>{policy.levels.length} level{policy.levels.length===1?'':'s'}{policy.locationId?' · location-specific':''}</span></button>)}</aside><main>
    <div className="approval-policy-grid"><label>Exception type<select value={draft.operationType} onChange={(event)=>{const operationType=event.target.value as Operation;setDraft({...draft,operationType,name:operations[operationType]});}}>{Object.entries(operations).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Policy name<input value={draft.name} onChange={(event)=>setDraft({...draft,name:event.target.value})}/></label><label>Location<select value={draft.locationId} onChange={(event)=>setDraft({...draft,locationId:event.target.value})}><option value="">All locations</option>{locations.map((location)=><option value={location.id} key={location.id}>{location.name}</option>)}</select></label><label>Approval threshold<input type="number" min="0" step="0.01" value={draft.thresholdValue} onChange={(event)=>setDraft({...draft,thresholdValue:Number(event.target.value)})}/></label></div>
    <label className="approval-policy-check"><input type="checkbox" checked={draft.blockSelfApproval} onChange={(event)=>setDraft({...draft,blockSelfApproval:event.target.checked})}/>Prevent creators from approving their own request</label><h2>Approval route</h2><div className="approval-policy-levels">{draft.levels.map((level,index)=><article key={index}><header><strong>Level {index+1}</strong>{draft.levels.length>1&&<button type="button" onClick={()=>setDraft({...draft,levels:draft.levels.filter((_,i)=>i!==index).map((item,i)=>({...item,level:i+1}))})}>Remove</button>}</header><div className="approval-policy-grid"><label>Label<input value={level.label} onChange={(event)=>patchLevel(index,{label:event.target.value})}/></label><label>Starts at value<input type="number" min="0" value={level.minValue} onChange={(event)=>patchLevel(index,{minValue:Number(event.target.value)})}/></label><label>Approvals required<input type="number" min="1" max="10" value={level.approvalsRequired} onChange={(event)=>patchLevel(index,{approvalsRequired:Number(event.target.value)})}/></label></div><fieldset><legend>Authorised roles and limits</legend>{roles.map((role)=>{const selected=level.roles.includes(role);return <div key={role}><label><input type="checkbox" checked={selected} onChange={()=>patchLevel(index,{roles:selected?level.roles.filter((item)=>item!==role):[...level.roles,role],roleLimits:selected?Object.fromEntries(Object.entries(level.roleLimits).filter(([key])=>key!==role)):{...level.roleLimits,[role]:null}})}/>{role}</label>{selected&&<input aria-label={`${role} approval limit`} type="number" min="0" placeholder="No limit" value={level.roleLimits[role]??''} onChange={(event)=>patchLevel(index,{roleLimits:{...level.roleLimits,[role]:event.target.value===''?null:Number(event.target.value)}})}/>}</div>})}</fieldset></article>)}</div><button type="button" className="approval-level-add" onClick={()=>setDraft({...draft,levels:[...draft.levels,{level:draft.levels.length+1,label:`Level ${draft.levels.length+1} approval`,minValue:0,maxValue:null,approvalsRequired:1,roles:[],roleLimits:{}}]})}>Add approval level</button><div className="approval-policy-actions">{draft.id&&<button type="button" onClick={async()=>{setBusy(true);try{await api(`approval-policies/${encodeURIComponent(draft.id!)}`,{method:'DELETE'});setDraft(blank());setMessage('Policy deactivated.');await load();}finally{setBusy(false);}}}>Deactivate</button>}<button type="button" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save policy'}</button></div>
  </main></div></section>;
}
