import { useCallback, useEffect, useMemo, useState } from 'react';

type View = 'all'|'location'|'role_set'|'user'|'overdue'|'waiting'|'blocked'|'completed'|'high_impact'|'unassigned';
type Action = any;
type Props = { api: <T>(resource: string, options?: { method?: 'GET'|'POST'; payload?: unknown; query?: Record<string,string> }) => Promise<T>; locations: Array<{ id: string; name: string }>; assignmentOptions: Array<{ type: 'user'|'role'|'location'; id: string; label: string }>; onOpenSource?: (deepLink: string) => void; };
const views: Array<[View,string]> = [['all','All'],['location','By location'],['role_set','By Role Set'],['user','By user'],['overdue','Overdue'],['waiting','Waiting'],['blocked','Blocked'],['completed','Completed'],['high_impact','High impact'],['unassigned','Unassigned']];

export function KcpFlowOperationsControl({ api, locations, assignmentOptions, onOpenSource }: Props) {
  const [view,setView]=useState<View>('all'); const [locationId,setLocationId]=useState(''); const [actions,setActions]=useState<Action[]>([]); const [metrics,setMetrics]=useState<any>(null); const [selected,setSelected]=useState<Action|null>(null); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);try { const r=await api<any>('actions/manager/control',{query:{view,...(locationId?{locationId}:{})}});setActions(r.actions||[]);setMetrics(r.metrics||null);} catch {setMessage('Operations Control could not be loaded.');} finally {setLoading(false);}},[api,locationId,view]);
  useEffect(()=>{void load();},[load]);
  async function intervene(operation: string, payload: Record<string,unknown>) { if(!selected)return; const reason=String(payload.reason||'').trim(); if(['reassign','escalate','defer','priority','resolve_blocker'].includes(operation)&&!reason){setMessage('A manager reason is required for this intervention.');return;} try { await api(`actions/manager/actions/${encodeURIComponent(selected.id)}/${operation}`,{method:'POST',payload}); setMessage('Action updated and recorded in its immutable Activity history.'); setSelected(null); await load(); } catch {setMessage('The Action could not be updated. Refresh and try again.');} }
  const cards=useMemo(()=>[{label:'Completion rate',value:metrics?`${metrics.completionRate}%`:'—'},{label:'Average completion',value:metrics?.averageCompletionMinutes==null?'—':`${metrics.averageCompletionMinutes} min`},{label:'Overdue rate',value:metrics?`${metrics.overdueRate}%`:'—'},{label:'Impact resolved',value:metrics?money(metrics.financialImpactResolved,metrics.currency):'—'}],[metrics]);
  return <section className="kcp-operations-control"><header><div><p>KCP Flow</p><h1>Operations Control</h1><span>See what needs attention and intervene without chasing each location.</span></div><button type="button" onClick={()=>void load()}>Refresh</button></header>{message&&<div role="status">{message}</div>}
    <div className="kcp-operation-metrics">{cards.map(card=><article key={card.label}><small>{card.label}</small><strong>{card.value}</strong></article>)}</div>
    <div className="kcp-operation-filters"><select value={view} onChange={e=>setView(e.target.value as View)}>{views.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">All permitted locations</option>{locations.map(location=><option value={location.id} key={location.id}>{location.name}</option>)}</select></div>
    <div className="kcp-operation-layout"><main><h2>{views.find(item=>item[0]===view)?.[1]} Actions</h2>{loading?<p>Loading operational view…</p>:actions.length?<div className="kcp-operation-actions">{actions.map(action=><button type="button" key={action.id} onClick={()=>setSelected(action)}><b>{action.title}</b><span>{action.location?.name||'No location'} · {action.assignment?.label||'Unassigned'}</span><small>{label(action.status)} · {label(action.priority)} priority · due {date(action.dueAt)}</small>{action.financialImpact&&<em>{money(action.financialImpact.amount,action.financialImpact.currency)}</em>}</button>)}</div>:<p>No Actions match this view.</p>}</main><aside><h2>Operational measurements</h2><Metric label="Deferred Actions" value={metrics?.deferredActions}/><Metric label="Rejected submissions" value={metrics?.rejectedSubmissions}/><Metric label="Approval turnaround" value={metrics?.approvalTurnaroundMinutes==null?'—':`${metrics.approvalTurnaroundMinutes} min`}/><h3>Location readiness</h3>{metrics?.locationReadiness?.map((item:any)=><p key={item.locationId}><b>{item.locationName}</b><span>{item.readiness}% ready · {item.overdueActions} overdue</span></p>)}<h3>Workload</h3>{metrics?.workload?.map((item:any)=><p key={item.key}><b>{item.label}</b><span>{item.openActions} open · {item.overdueActions} overdue</span></p>)}</aside></div>
    {selected&&<ActionControl action={selected} assignmentOptions={assignmentOptions} onClose={()=>setSelected(null)} onOpenSource={onOpenSource} onIntervene={intervene}/>}</section>;
}
function ActionControl({action,assignmentOptions,onClose,onOpenSource,onIntervene}:{action:Action;assignmentOptions:Props['assignmentOptions'];onClose:()=>void;onOpenSource?:Props['onOpenSource'];onIntervene:(operation:string,payload:Record<string,unknown>)=>void}){const [reason,setReason]=useState('');const [assignment,setAssignment]=useState('');const [priority,setPriority]=useState(action.priority);return <div className="kcp-operation-drawer" role="dialog" aria-modal="true"><article><header><div><p>KCP Flow Action</p><h2>{action.title}</h2></div><button type="button" onClick={onClose}>Close</button></header><p>{action.description||'No additional description.'}</p><dl><dt>Status</dt><dd>{label(action.status)}</dd><dt>Assignment</dt><dd>{action.assignment?.label||'Unassigned'}</dd><dt>Due</dt><dd>{date(action.dueAt)}</dd><dt>Progress</dt><dd>{action.progress?.percent||0}%</dd></dl>{action.evidence?.length?<section><h3>Evidence</h3>{action.evidence.map((e:any)=><p key={e.id}>{e.fileName} · {e.createdByName||'KCP user'}</p>)}</section>:null}<label>Manager reason<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required for every intervention" /></label><div className="kcp-manager-controls"><label>Reassign<select value={assignment} onChange={e=>setAssignment(e.target.value)}><option value="">Choose authorised user or Role Set</option>{assignmentOptions.filter(option=>option.type!=='location').map(option=><option value={`${option.type}:${option.id}:${option.label}`} key={`${option.type}:${option.id}`}>{option.label}</option>)}</select></label><button type="button" disabled={!assignment} onClick={()=>{const [type,targetId,label]=assignment.split(':');onIntervene('reassign',{type,targetId,label,reason});}}>Reassign</button><button type="button" onClick={()=>onIntervene('escalate',{reason})}>Escalate</button><button type="button" onClick={()=>onIntervene('defer',{reason})}>Defer</button><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}>{['low','normal','high','urgent'].map(value=><option key={value}>{value}</option>)}</select></label><button type="button" onClick={()=>onIntervene('priority',{priority,reason})}>Change priority</button><button type="button" onClick={()=>onIntervene('resolve_blocker',{reason})}>Resolve blocker</button>{onOpenSource&&<button type="button" onClick={()=>onOpenSource(action.deepLink)}>Open source transaction</button>}</div><section><h3>Complete Activity history</h3>{action.activityHistory?.length?action.activityHistory.map((event:any)=><p key={event.id}><b>{label(event.eventType)}</b> · {event.actorName} · {date(event.occurredAt)}<br/>{event.detail}</p>):<p>Open the Action record to inspect its full Activity history.</p>}</section></article></div>}
function Metric({label,value}:{label:string;value:any}){return <p><b>{label}</b><span>{value??'—'}</span></p>} function label(value:string){return String(value||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());} function date(value:string){return new Intl.DateTimeFormat('en-ZA',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value));} function money(value:number,currency='ZAR'){return new Intl.NumberFormat('en-ZA',{style:'currency',currency}).format(value);}
