import { useEffect, useMemo, useState } from 'react';
import './RoleSetsAdmin.css';

type RoleSet = { id:string;name:string;description:string;preferredActionTypes:string[];priorityOrder:string[];defaultShortcuts:string[];financialVisibility:'none'|'material_only'|'full';locationIds:string[];assignmentRule:'assigned_only'|'user_or_role_set'|'location_operations';canReassign:boolean;canDefer:boolean;escalation:{afterMinutes:number;minimumPriority:string;financialThreshold?:number|null};active:boolean;system:boolean;assignedCount?:number };
type User = { id:string;name:string;email?:string;roleSetId?:string };
type Props = { api:<T>(resource:string,options?:{method?:'GET'|'POST'|'PUT';payload?:unknown})=>Promise<T>; users:User[]; locations:Array<{id:string;name:string}> };

export function RoleSetsAdmin({api,users,locations}:Props){
  const [items,setItems]=useState<RoleSet[]>([]); const [selected,setSelected]=useState(''); const [query,setQuery]=useState(''); const [userQuery,setUserQuery]=useState(''); const [message,setMessage]=useState('');
  const active=items.find((item)=>item.id===selected)||null;
  const filtered=useMemo(()=>items.filter((item)=>`${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
  const filteredUsers=useMemo(()=>users.filter((user)=>`${user.name} ${user.email||''}`.toLowerCase().includes(userQuery.toLowerCase())),[users,userQuery]);
  const load=()=>api<{roleSets:RoleSet[]}>('role-sets').then((response)=>{setItems(response.roleSets);setSelected((current)=>current||response.roleSets[0]?.id||'');});
  useEffect(()=>{void load();},[]);
  function update(patch:Partial<RoleSet>){setItems((current)=>current.map((item)=>item.id===selected?{...item,...patch}:item));}
  async function save(){if(!active)return;setMessage('');await api(`role-sets/${encodeURIComponent(active.id)}`,{method:'PUT',payload:active});setMessage('Role Set saved. Permissions and user location access remain unchanged.');await load();}
  async function assign(userId:string,roleSetId:string){await api(`role-set-assignments/${encodeURIComponent(userId)}`,{method:'PUT',payload:{roleSetId}});setMessage('User Role Set updated.');}
  function create(){const id=`custom-${Date.now()}`;const item:RoleSet={id,name:'New Role Set',description:'',preferredActionTypes:['routine_checklist'],priorityOrder:['urgent','high','normal','low'],defaultShortcuts:['tasks'],financialVisibility:'none',locationIds:['all'],assignmentRule:'assigned_only',canReassign:false,canDefer:false,escalation:{afterMinutes:60,minimumPriority:'high',financialThreshold:null},active:true,system:false,assignedCount:0};setItems((current)=>[item,...current]);setSelected(id);}
  return <section className="role-sets-admin"><header><div><p>KCP User Actions</p><h1>Role Sets</h1><span>Prioritise each mobile experience without replacing permissions.</span></div><div className="role-set-header-actions"><button type="button" className="secondary" onClick={create}>New Role Set</button><button type="button" onClick={()=>void save()} disabled={!active}>Save Role Set</button></div></header>{message&&<div className="role-set-message" role="status">{message}</div>}
    <div className="role-set-layout"><aside><label>Find a Role Set<input type="search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search 10+ Role Sets" /></label><div className="role-set-selector" role="listbox" aria-label="Role Sets">{filtered.map((item)=><button type="button" role="option" aria-selected={item.id===selected} className={item.id===selected?'is-active':''} key={item.id} onClick={()=>setSelected(item.id)}><span><strong>{item.name}</strong><small>{item.assignedCount||0} users · {item.system?'Built in':'Custom'}</small></span><b>{item.active?'Active':'Off'}</b></button>)}</div></aside>
      <main>{active&&<><div className="role-set-fields"><label>Name<input value={active.name} onChange={(event)=>update({name:event.target.value})} /></label><label>Description<textarea value={active.description} onChange={(event)=>update({description:event.target.value})} /></label><label>Financial information<select value={active.financialVisibility} onChange={(event)=>update({financialVisibility:event.target.value as RoleSet['financialVisibility']})}><option value="none">Hidden</option><option value="material_only">Material exceptions only</option><option value="full">Full financial detail</option></select></label><label>Assignment rules<select value={active.assignmentRule} onChange={(event)=>update({assignmentRule:event.target.value as RoleSet['assignmentRule']})}><option value="assigned_only">Assigned Actions only</option><option value="user_or_role_set">User or Role Set</option><option value="location_operations">Location operations</option></select></label><label>Preferred Action types<input value={active.preferredActionTypes.join(', ')} onChange={(event)=>update({preferredActionTypes:split(event.target.value)})} /></label><label>Default mobile shortcuts<input value={active.defaultShortcuts.join(', ')} onChange={(event)=>update({defaultShortcuts:split(event.target.value)})} /></label><label>Locations<select multiple value={active.locationIds} onChange={(event)=>update({locationIds:Array.from(event.target.selectedOptions,(option)=>option.value)})}><option value="all">All permission-authorised locations</option>{locations.map((location)=><option value={location.id} key={location.id}>{location.name}</option>)}</select></label><label>Escalate after minutes<input type="number" min="0" value={active.escalation.afterMinutes} onChange={(event)=>update({escalation:{...active.escalation,afterMinutes:Number(event.target.value)}})} /></label><label>Material value threshold<input type="number" min="0" value={active.escalation.financialThreshold??''} onChange={(event)=>update({escalation:{...active.escalation,financialThreshold:event.target.value===''?null:Number(event.target.value)}})} /></label></div><div className="role-set-switches"><label><input type="checkbox" checked={active.canReassign} onChange={(event)=>update({canReassign:event.target.checked})} /> May reassign Actions</label><label><input type="checkbox" checked={active.canDefer} onChange={(event)=>update({canDefer:event.target.checked})} /> May defer Actions</label><label><input type="checkbox" checked={active.active} onChange={(event)=>update({active:event.target.checked})} /> Active</label></div>
        <section className="role-set-users"><header><div><h2>Assign users</h2><p>The user's existing permissions and locations still win.</p></div><input type="search" value={userQuery} onChange={(event)=>setUserQuery(event.target.value)} placeholder="Search users" /></header>{filteredUsers.map((user)=><div key={user.id}><span><strong>{user.name}</strong><small>{user.email}</small></span><select defaultValue={user.roleSetId||''} onChange={(event)=>void assign(user.id,event.target.value)}><option value="" disabled>Choose Role Set</option>{items.filter((item)=>item.active).map((item)=><option value={item.id} key={item.id}>{item.name}</option>)}</select></div>)}</section></>}</main>
    </div>
  </section>;
}
function split(value:string){return value.split(',').map((item)=>item.trim()).filter(Boolean);}
